[project]
name = "server"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "deep-translator>=1.11.4",
    "opencv-python>=5.0.0.93",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "ultralytics>=8.4.138",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 88
indent-width = 2

[tool.ruff.format]
quote-style = 'single'
indent-style = 'space'
line-ending = 'lf'

[tool.ruff.lint]
select = [
    'E',
    'F',
    'I',
    'UP',
    'B',
]